import socket
from scapy.all import *

# Set the server IP address and port
SERVER_IP = "10.129.131.233"
SERVER_PORT = 5000

# Function to modify the payload of captured UDP packets
def modify_payload(packet):
    # Implement payload modification logic here
    # For demonstration, we'll simply prepend "Modified: " to the payload
    modified_payload = b"Modified: " + packet[UDP].payload
    packet[UDP].payload = modified_payload
    del packet[IP].len
    del packet[IP].chksum
    del packet[UDP].chksum
    return packet

# Callback function to process captured UDP packets
def packet_callback(packet):
    if packet.haslayer(UDP):
        modified_packet = modify_payload(packet)
        send(modified_packet, verbose=False)

# Start sniffing UDP packets generated by netperf
sniff(filter="udp and host " + SERVER_IP, prn=packet_callback)

# Wait for a keypress to stop sniffing
input("Press Enter to stop sniffing...")
